version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: pfcti-database
    environment:
      MYSQL_ROOT_PASSWORD: pfctipassword
      MYSQL_DATABASE: pfcti
      MYSQL_USER: pfcti_user
      MYSQL_PASSWORD: pfctiuserpassword
    ports:
      - "3306:3306"
    networks:
      - pfcti-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: technical-test
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://pfcti-database:3306/pfcti
      SPRING_DATASOURCE_USERNAME: pfcti_user
      SPRING_DATASOURCE_PASSWORD: pfctiuserpassword	
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - pfcti-network

networks:
  pfcti-network:
    driver: bridge

volumes:
  mysql-data:
